<?php

namespace ContainerJEyIxkL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DEvZXs5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dEvZXs5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dEvZXs5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'operateur' => ['privates', '.errored..service_locator.dEvZXs5.App\\Entity\\Operateurs', NULL, 'Cannot autowire service ".service_locator.dEvZXs5": it references class "App\\Entity\\Operateurs" but no such service exists.'],
            'operateursRepository' => ['privates', 'App\\Repository\\OperateursRepository', 'getOperateursRepositoryService', true],
        ], [
            'operateur' => 'App\\Entity\\Operateurs',
            'operateursRepository' => 'App\\Repository\\OperateursRepository',
        ]);
    }
}
