<?php

namespace Container2Tl5tN3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VHkAjcuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vHkAjcu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vHkAjcu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activite' => ['privates', '.errored..service_locator.vHkAjcu.App\\Entity\\Activites', NULL, 'Cannot autowire service ".service_locator.vHkAjcu": it references class "App\\Entity\\Activites" but no such service exists.'],
            'activitesRepository' => ['privates', 'App\\Repository\\ActivitesRepository', 'getActivitesRepositoryService', true],
        ], [
            'activite' => 'App\\Entity\\Activites',
            'activitesRepository' => 'App\\Repository\\ActivitesRepository',
        ]);
    }
}
