<?php

namespace Container2Tl5tN3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JkrcIJYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JkrcIJY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JkrcIJY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repoCategories' => ['privates', 'App\\Repository\\CategoriesRepository', 'getCategoriesRepositoryService', true],
            'repoOperateurs' => ['privates', 'App\\Repository\\OperateursRepository', 'getOperateursRepositoryService', true],
        ], [
            'repoCategories' => 'App\\Repository\\CategoriesRepository',
            'repoOperateurs' => 'App\\Repository\\OperateursRepository',
        ]);
    }
}
