<?php

namespace ContainerSxLerqB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cz1pa2bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Cz1pa2b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cz1pa2b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'operateur' => ['privates', '.errored..service_locator.Cz1pa2b.App\\Entity\\Operateurs', NULL, 'Cannot autowire service ".service_locator.Cz1pa2b": it references class "App\\Entity\\Operateurs" but no such service exists.'],
        ], [
            'operateur' => 'App\\Entity\\Operateurs',
        ]);
    }
}
