<?php

namespace Container41xsJay;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AyhEty_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ayhEty.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ayhEty.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activitesRepository' => ['privates', 'App\\Repository\\ActivitesRepository', 'getActivitesRepositoryService', true],
        ], [
            'activitesRepository' => 'App\\Repository\\ActivitesRepository',
        ]);
    }
}
