<?php

namespace Container41xsJay;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivites2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vHkAjcu.App\Entity\Activites' shared service.
     *
     * @return \App\Entity\Activites
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.vHkAjcu": it references class "App\\Entity\\Activites" but no such service exists.');
    }
}
