<?php

namespace ContainerHU0KvYx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JQZgjVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JQ_ZgjV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JQ_ZgjV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activite' => ['privates', '.errored..service_locator.JQ_ZgjV.App\\Entity\\Activites', NULL, 'Cannot autowire service ".service_locator.JQ_ZgjV": it references class "App\\Entity\\Activites" but no such service exists.'],
        ], [
            'activite' => 'App\\Entity\\Activites',
        ]);
    }
}
