<?php

namespace ContainerLllwzZ9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WLJWiJMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wLJWiJM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wLJWiJM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoriesRepository' => ['privates', 'App\\Repository\\CategoriesRepository', 'getCategoriesRepositoryService', true],
            'category' => ['privates', '.errored..service_locator.wLJWiJM.App\\Entity\\Categories', NULL, 'Cannot autowire service ".service_locator.wLJWiJM": it references class "App\\Entity\\Categories" but no such service exists.'],
        ], [
            'categoriesRepository' => 'App\\Repository\\CategoriesRepository',
            'category' => 'App\\Entity\\Categories',
        ]);
    }
}
