<?php

namespace ContainerC2KVz7c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOperateurs2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dEvZXs5.App\Entity\Operateurs' shared service.
     *
     * @return \App\Entity\Operateurs
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.dEvZXs5": it references class "App\\Entity\\Operateurs" but no such service exists.');
    }
}
