<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEnbqYwb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEnbqYwb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEnbqYwb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEnbqYwb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEnbqYwb\App_KernelDevDebugContainer([
    'container.build_hash' => 'EnbqYwb',
    'container.build_id' => '856b07c8',
    'container.build_time' => 1664458862,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEnbqYwb');
