<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJEyIxkL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJEyIxkL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJEyIxkL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJEyIxkL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJEyIxkL\App_KernelDevDebugContainer([
    'container.build_hash' => 'JEyIxkL',
    'container.build_id' => '9b5ffb11',
    'container.build_time' => 1663233371,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJEyIxkL');
