<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_activites_index' => [[], ['_controller' => 'App\\Controller\\ActivitesController::index'], [], [['text', '/activites/']], [], [], []],
    'app_activites_new' => [[], ['_controller' => 'App\\Controller\\ActivitesController::new'], [], [['text', '/activites/new']], [], [], []],
    'app_activites_show' => [['id'], ['_controller' => 'App\\Controller\\ActivitesController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/activites']], [], [], []],
    'app_activites_edit' => [['id'], ['_controller' => 'App\\Controller\\ActivitesController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/activites']], [], [], []],
    'app_activites_delete' => [['id'], ['_controller' => 'App\\Controller\\ActivitesController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/activites']], [], [], []],
    'artisan' => [['id'], ['id' => 3, '_controller' => 'App\\Controller\\ArtisanController::artisan'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/artisan/id']], [], [], []],
    'back' => [[], ['_controller' => 'App\\Controller\\BackOfficeController::back'], [], [['text', '/back']], [], [], []],
    'app_categories_index' => [[], ['_controller' => 'App\\Controller\\CategoriesController::index'], [], [['text', '/categories/']], [], [], []],
    'app_categories_new' => [[], ['_controller' => 'App\\Controller\\CategoriesController::new'], [], [['text', '/categories/new']], [], [], []],
    'app_categories_show' => [['id'], ['_controller' => 'App\\Controller\\CategoriesController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/categories']], [], [], []],
    'app_categories_edit' => [['id'], ['_controller' => 'App\\Controller\\CategoriesController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/categories']], [], [], []],
    'app_categories_delete' => [['id'], ['_controller' => 'App\\Controller\\CategoriesController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/categories']], [], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::contact'], [], [['text', '/contact']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], [], [['text', '/']], [], [], []],
    'app_operateurs_index' => [[], ['_controller' => 'App\\Controller\\OperateursController::index'], [], [['text', '/operateurs/']], [], [], []],
    'app_operateurs_new' => [[], ['_controller' => 'App\\Controller\\OperateursController::new'], [], [['text', '/operateurs/new']], [], [], []],
    'app_operateurs_show' => [['id'], ['_controller' => 'App\\Controller\\OperateursController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/operateurs']], [], [], []],
    'app_operateurs_edit' => [['id'], ['_controller' => 'App\\Controller\\OperateursController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/operateurs']], [], [], []],
    'app_operateurs_delete' => [['id'], ['_controller' => 'App\\Controller\\OperateursController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/operateurs']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
