<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_activites' => [[], ['_controller' => 'App\\Controller\\ActivitesController::index'], [], [['text', '/activites']], [], [], []],
    'app_categories' => [[], ['_controller' => 'App\\Controller\\CategoriesController::index'], [], [['text', '/categories']], [], [], []],
    'app_operateurs' => [[], ['_controller' => 'App\\Controller\\OperateursController::index'], [], [['text', '/operateurs']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
